### ISSUE TITLE
[Bug] Cannot inintialize shell with correct path variables on Windows

### ISSUE THREAD

**Issue by cworld1** [ekzhang/sshx#101]
## Description

In normal terminal application like Windows terminal, can correctly read user path or system path, but sshx cannot instead.

![image](https://github.com/user-attachments/assets/ff3ebf35-d134-4879-98f2-b2d3377faea2)

## Try other way

I tried `pwsh` instead of `fish`, I got a new problem:

![image](https://github.com/user-attachments/assets/52588fbc-900f-453b-803c-6ab20162c53e)

```log
Process terminated. The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)       
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
 ---> System.ComponentModel.Win32Exception (126): The specified module could not be found.
   at System.Management.Automation.Internal.SecuritySupport.GetSaferPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.TestSaferPolicy(String testPathScript, String testPathModule)
   at System.Management.Automation.Security.SystemPolicy.GetAppLockerPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetLockdownPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy()
   at System.Management.Automation.Runspaces.InitialSessionState..cctor()       
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
```

And I tried `cmd` instead, telling me cannot find executable application on the path.

![image](https://github.com/user-attachments/assets/318c3231-612c-4ac4-a2bc-a02a453f613c)

**Comment by ekzhang** [comment]
Thanks for the bug report! I've also seen this happen with Powershell on Windows, and I'm not sure why. It works with cmd.exe though and Git Bash.

Not sure how to set these environment variables properly so that Powershell can boot as a spawned process.

**Comment by cworld1** [comment]
My point I want to convey is that all of these terminals have the problem of not inheriting Windows system environment variables.
PowerShell is actually more problematic, but I don't use it very often.

**Comment by ekzhang** [comment]
Okay! Let me know if you'd like to contribute a fix for this.

I honestly don't know how Windows works at all

**Comment by QiWei** [comment]
The issue lies in `command.get_envs()`. [The documentation](https://doc.rust-lang.org/std/process/struct.Command.html#method.get_envs) states:

`get_envs()` Returns an iterator of the environment variables explicitly set for the child process.

Environment variables explicitly set using [Command::env](https://doc.rust-lang.org/std/process/struct.Command.html#method.env), [Command::envs](https://doc.rust-lang.org/std/process/struct.Command.html#method.envs), and [Command::env_remove](https://doc.rust-lang.org/std/process/struct.Command.html#method.env_remove) can be retrieved with this method.

Note that this output does not include environment variables inherited from the parent process.

You can fix this issue with the following code:
```diff
diff --git a/crates/sshx/src/terminal/windows.rs b/crates/sshx/src/terminal/windows.rs
index 094ff38..b732b4c 100644
--- a/crates/sshx/src/terminal/windows.rs
+++ b/crates/sshx/src/terminal/windows.rs
@@ -46,6 +46,11 @@ impl Terminal {
     pub async fn new(shell: &str) -> Result<Terminal> {
         let mut command = Command::new(shell);
 
+        // Inherit all environment variables from the parent process
+        for (key, value) in std::env::vars() {
+            command.env(key, value);
+        }
+
         // Set terminal environment variables appropriately.
         command.env("TERM", "xterm-256color");
         command.env("COLORTERM", "truecolor");
```
